// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZtCnCIYrJCT6BF3D3vrIv7Yy4sIq3LDo',
    appId: '1:545950721467:web:3caaa9c9af4e854b12909e',
    messagingSenderId: '545950721467',
    projectId: 'kidsbank-45877',
    authDomain: 'kidsbank-45877.firebaseapp.com',
    storageBucket: 'kidsbank-45877.firebasestorage.app',
    measurementId: 'G-YRVH3BFB5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2T-WpcjxKcsBZJ4mPn7mXE5tFVATAKQ',
    appId: '1:545950721467:android:251b00124b3417fe12909e',
    messagingSenderId: '545950721467',
    projectId: 'kidsbank-45877',
    storageBucket: 'kidsbank-45877.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhiBuACYwEkBnuGonOomSFnVR_VKiE2xU',
    appId: '1:545950721467:ios:f55c7a57e8249fa112909e',
    messagingSenderId: '545950721467',
    projectId: 'kidsbank-45877',
    storageBucket: 'kidsbank-45877.firebasestorage.app',
    iosClientId: '545950721467-opjfag64c1g1d2re54g414re710vlqjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wfinalsKidsbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhiBuACYwEkBnuGonOomSFnVR_VKiE2xU',
    appId: '1:545950721467:ios:f55c7a57e8249fa112909e',
    messagingSenderId: '545950721467',
    projectId: 'kidsbank-45877',
    storageBucket: 'kidsbank-45877.firebasestorage.app',
    iosClientId: '545950721467-opjfag64c1g1d2re54g414re710vlqjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wfinalsKidsbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZtCnCIYrJCT6BF3D3vrIv7Yy4sIq3LDo',
    appId: '1:545950721467:web:8deecb11179e8b6412909e',
    messagingSenderId: '545950721467',
    projectId: 'kidsbank-45877',
    authDomain: 'kidsbank-45877.firebaseapp.com',
    storageBucket: 'kidsbank-45877.firebasestorage.app',
    measurementId: 'G-7S36MWS6DS',
  );
}
